### PR TITLE
Carthage support

### PR DESCRIPTION
**Pull request by cfdrake**
Hello!

To start: great library! I went to use this today on my Carthage-driven project and noticed the only supported methods of installation were Cocoapods and drag-and-drop, so I got to work. :)

This pull request adds an `.xcodeproj` with a shared iOS and Mac OS X Framework target. I've attempted to get this working with the most minimal changes to the original source/structure so as not to affect others using KZPropertyMapper via other installation methods.

I've tested this with the latest Xcode 7 build and Carthage version 0.8 (`brew upgrade carthage` to fetch, if needed).

All you need to do to get this working in an example project is have a `Cartfile` with the following contents:

`github "cfdrake/KZPropertyMapper" "master"`

From here, run `carthage bootstrap`. You'll see there is a `.framework` file in both `Carthage/Build/iOS` and `Carthage/Build/Mac`. You can now follow the instructions on the [Carthage README](https://github.com/Carthage/Carthage#adding-frameworks-to-an-application) to include the compiled frameworks in an app. After doing this, a simple `@import KZPropertyMapper` at the top of your source file should include the relevant header files.

Let me know if this seems to be working/you have any suggestions/you're open to adding support for this dependency manager. Thanks!

### CODE REVIEW

**Comment by lottadot** [comment]
@cfdrake No README w/ additional carthage information?

**Comment by cfdrake** [comment]
I updated the `README` with Carthage instructions as well as a few more clarifying details.

Note: It looks like I was mistaken in my assumptions above - Carthage _0.9_, not _0.8_, supports universal Mac OS X/iOS Framework targets. However, Carthage 0.8 is the currently distributed release via Homebrew. So for now, I'll need to modify this pull request to create two framework targets, one for each platform. Will comment once this is ready!

**Comment by cfdrake** [comment]
Alright - I think I got this sorted out and tested properly now :) We've now got two targets, KZPropertyMapperIOS and KZPropertyMapperOSX that each output a `KZPropertyMapper.framework` file when built.

If you run `carthage bootstrap` you'll get output in both `iOS` and `Mac` folders as specified above, and you can use `--platform iOS`, etc. to build per-platform if desired.

Let me know if you run across any issues - thanks!

**Comment by krzysztofzablocki** [comment]
awesome, thanks!

**Pull request merged**
