### PR TITLE
Block should be copied before storing its reference.

### PR DESCRIPTION
**Pull request by lxcid**

### CODE REVIEW

**Comment by krzysztofzablocki** [comment]
didn't LLVM do block copy automatically for a while?

**Comment by lxcid** [comment]
I'm unaware of the behaviour though. Any docs pointing to that? Interested to read more about it!

**Comment by krzysztofzablocki** [comment]
http://clang.llvm.org/docs/AutomaticReferenceCounting.html#blocks

> With the exception of retains done as part of initializing a __strong parameter variable or reading a __weak variable, whenever these semantics call for retaining a value of block-pointer type, it has the effect of a Block_copy. The optimizer may remove such copies when it sees that the result is used only as an argument to a call.

I usually copy anyway since it doesn't have penalty but it shouldn't affect it

**Comment by lxcid** [comment]
Oh wow, that's interesting to know. Thanks! Closing.

**Pull request closed without merging**
